package me.footlights.demo.plugins.good;

import me.footlights.plugin.AjaxHandler;
import me.footlights.plugin.JavaScript;
import me.footlights.plugin.WebRequest;


/** A demonstration of what a {@link Plugin}'s {@link AjaxHandler} can do. */
class DemoAjaxHandler implements AjaxHandler
{
	@Override
	public JavaScript service(WebRequest request)
	{
		return new JavaScript()
			.append("context.root.appendElement('div')")
			.append(".appendText('This text generated by ")
			.append(GoodPlugin.class.getCanonicalName())
			.append(" in response to request \"")
			.append(JavaScript.sanitizeText(request.path()))
			.append("\"')");
	}

}
